window.magic_trans={
    "bare shoulders": "裸露的肩膀",
    "extremely detailed eyes": "极其细致的眼睛",
    "bad hairs": "头发不好",
    "Clothes with gold lace": "带金色蕾丝的衣服",
    "black clit": "黑色yin蒂",
    "halo": "光环",
    "boken limb": "短肢",
    "cold face and white shirt": "冷面白衬衫",
    "colorful tongue": "彩色舌头",
    "dark magician girl:1.1": "黑暗魔术师女孩：1.1",
    "full body": "全身2",
    "dark magician girl": "黑暗魔术师女孩",
    "A burning church": "燃烧的教堂",
    "detailed shadow": "详细阴影",
    "more than 1 left hand": "超过1只左手",
    "jpeg  artifacts": "jpeg工件",
    "extremely detailed CG unity 8k wallpaper": "非常详细的CG unity 8k壁纸",
    "white bowties": "白色蝴蝶结",
    "extra thighs": "额外的大腿",
    "floating flow": "浮动流量",
    "extremely beautiful detailed anime face and eyes": "极其美丽细致的动漫脸和眼睛",
    "frills": "虚饰",
    "everything flowing and melt": "一切都在流动和融化",
    "dramatic angle": "戏剧性角度",
    "1": "1.",
    "2": "2.",
    "very long rainbow hair": "很长的彩虹头发",
    "glass strips": "玻璃条",
    "floating palaces": "浮动宫殿",
    "missing arms": "丢失的手臂",
    "translucent pink skirt": "半透明粉色裙子",
    "bad finglegs": "坏燕雀",
    "poorly drawn pussy": "画得不好的阴部",
    "white hair/yellow eyes": "白发/黄眼睛",
    "pony": "小马",
    "wind": "风",
    "sideboob": "侧边栏",
    "safety knickers": "安全内裤",
    "gemstone sea": "宝石海",
    "forest": "森林",
    "Bloody scenes": "血腥场面",
    "cliff": "悬崖",
    "jpegartifacts": "jpegartifacts（jpegaartifacts）",
    "black and white sleeves": "黑白袖子",
    "poorly drawn hands": "画得不好的手",
    "glistening light of waves": "波光粼粼",
    "huge thighs": "巨大的大腿",
    "fine lighting": "精细照明",
    "gemological hair": "宝石学毛发",
    "split tentacles": "分裂触手",
    "deep dark": "深暗的",
    "hair flower": "发花",
    "Fluttering hair": "飘逸的头发",
    "jpeg": "jpeg格式",
    "low background": "低背景",
    "particle": "微粒",
    "gloom expression depressed": "忧郁的表情抑郁",
    "colorful bubble": "彩色气泡",
    "flowing hair": "飘逸的头发2",
    "bad anatomy disfigured": "解剖结构不良，毁容",
    "snow field": "雪地",
    "light smile": "淡淡的微笑",
    "blood": "血",
    "more than 1 right hand": "不止一只右手",
    "high ponytail": "高马尾辫",
    "outdoors": "在户外",
    "bad tongue": "口齿不好",
    "sunset": "日落",
    "bad knee": "膝盖不好",
    "Metal crown with ornate stripes": "带华丽条纹的金属皇冠",
    "beautiful face": "漂亮的脸",
    "illustration": "插图",
    "cloud map plane": "云地图平面",
    "dark dress": "深色连衣裙",
    "long black hair": "黑色长发",
    "posing": "摆姿势",
    "ribbon trimmed sleeves": "缎带装饰袖子",
    "extremely detailed dark clouds": "极其详细的乌云",
    "ace": "王牌",
    "beautiful detailed Glass hair": "漂亮细致的玻璃头发",
    "gothic architecture": "哥特式建筑",
    "red moon": "红色的月亮",
    "normal quality": "正常质量",
    "Snowflakes": "雪花2",
    "depthoffield": "德特霍菲尔德",
    "light shafts": "光线束",
    "cthulhu": "查尔胡",
    "spring": "春天",
    "bright eyes": "明亮的眼睛",
    "cool movement": "冷运动",
    "short legs": "短腿",
    "skyblue dress": "天蓝色连衣裙",
    "long hair floating everywhere": "长发飘得到处都是",
    "blush": "脸红",
    "lacy": "花边",
    "flat chest": "平胸",
    "crystals texture skin": "水晶质地皮肤",
    "fantasy": "幻想",
    "starry tornado:1.4": "星空龙卷风：1.4",
    "beautiful and detailed eyes": "美丽而细致的眼睛",
    "flat chst": "扁平chst",
    "1girl": "1个女孩",
    "volume": "体积",
    "shell": "壳",
    "looking at viewer": "查看查看器4",
    "ruins": "废墟",
    "hair bow": "头发弓",
    "cinematiclighting": "电影照明",
    "walking motion": "行走运动",
    "1girl:1.2": "女孩：1.2",
    "conch": "海螺",
    "far from viewer": "远离观众",
    "water spray": "喷水",
    "only upper body": "只有上半身",
    "Background of details": "详细信息的背景",
    "huge  crystal wings": "巨大的水晶翅膀",
    "cold face": "冷酷的面孔",
    "sharp focus": "锐利焦点",
    "Iridescence and rainbow hair:2.5": "彩虹色和彩虹色头发：2.5",
    "colorful clit": "彩色yin蒂",
    "disappearing thigh": "消失的大腿",
    "Beautiful butterflies in detail": "美丽的蝴蝶细节",
    "The finest grass. beautiful eyes": "最好的草。美丽的眼睛",
    "Mature": "成熟",
    "sliver and broken body": "条子和断体",
    "crystals texture Hair": "水晶质地头发",
    "bare shoulder": "裸肩",
    "short hair": "短发",
    "Crystallization of clothes": "衣服结晶",
    "disheveled hair": "蓬乱的头发",
    "Floating white silk": "漂浮的白色丝绸",
    "thick lips": "厚嘴唇",
    "white  hair": "白发2",
    "drenched": "湿透了",
    "portrait": "肖像",
    "bad feet": "脚不好",
    "fewer digits": "更少的数字",
    "beautiful detailed face": "美丽的细节脸",
    "Mecha wing": "Mecha翼",
    "beautiful detailed sky": "美丽详细的天空7",
    "serafuku": "塞拉夫库",
    "extra ears": "额外的耳朵",
    "missing calf": "失踪的小牛",
    "close to viewers": "靠近观众",
    "splash": "泼洒",
    "username": "用户名",
    "red pupils": "红色瞳孔",
    "indifference": "冷漠",
    "anatomical nonsense": "解剖学上的胡说八道",
    "black Headdress": "黑色头饰",
    "extremely detailed CG unity wallpaper": "非常详细的CG统一墙纸",
    "frozen feathers": "冻结的羽毛",
    "unexposed :1.5": "未暴露：1.5",
    "three legs": "三条腿",
    "gemstone of body": "身体宝石",
    "ribbons": "缎带",
    "darkness": "黑暗",
    "tidy classroom": "整洁的教室",
    "low quality light": "低质量光",
    "glossy hair": "光滑的头发",
    "beautiful and delicate water": "美丽而精致的水",
    "close to viewer": "靠近查看器",
    "disappearing calf": "消失的小牛",
    "Hands as clear as jewels": "手像珠宝一样清晰",
    "beautiful detailed glow": "美丽的细节辉光",
    "best illustration": "最佳插图",
    "messy long hair": "凌乱的长发",
    "bad shose": "坏鞋子2",
    "standard quality": "标准质量",
    "yellow full moon": "黄色满月",
    "fused calf": "融合小牛",
    "big face": "大脸",
    "highres": "高等教育",
    "mutation": "突变3",
    "submerge": "淹没",
    "bad proportions": "比例不好",
    "floating sand flow": "浮沙流",
    "malformed limbs": "畸形肢体",
    "yellow teeth": "黄色牙齿",
    "black ribbon": "黑色丝带",
    "air force fleet in the sky": "空中空军舰队",
    "floating and rainbow hair": "漂浮的彩虹头发",
    "expressionless": "无表情的",
    "Metal carving": "金属雕刻",
    "white idol dress": "白色偶像连衣裙",
    "delicate and intricate hair": "精致而复杂的头发",
    "long skirt": "长裙",
    "white dress with gold decoration": "金色装饰的白色连衣裙",
    "Negative prompt: multiple breasts": "阴性提示：多个乳房",
    "malformed": "畸形的",
    "bandage": "绷带",
    "bikini": "比基尼",
    "dramatic shadow": "戏剧性阴影",
    "out of frame": "帧外",
    "splashing water": "飞溅的水",
    "liquid collarbone": "液态锁骨",
    "Mechanical girl": "机械女孩",
    "snowflake": "雪花",
    "high quality mountains": "高品质山脉",
    "spirit": "精神",
    "different nipples": "不同的乳头",
    "large breasts": "大乳房",
    "lose finger": "失去手指",
    "hollow knight": "空心骑士",
    "crystals texture flowers": "晶体结构花",
    "bad shadow": "不良阴影",
    "half closed eyes\u0005": "半闭着的眼睛2",
    "near the water edge": "靠近水边",
    "rose": "玫瑰",
    "extra calf": "额外小腿",
    "Facing the lens": "面向镜头",
    "slit pupils": "狭缝瞳孔",
    "black nipples": "黑色乳头",
    "ahoge": "霍奇",
    "a girl": "一个女孩6",
    "very fine 8K CG wallpaper": "非常精致的8K CG壁纸",
    "hollow eyes": "空心的眼睛",
    "Loong": "龙",
    "mechanical body armor": "机械防弹衣",
    "poorly drawn breasts": "胸部拉伤",
    "very close to viewers": "非常接近观众",
    "grey hair": "灰色头发",
    "cage": "笼子",
    "whole body": "全身",
    "coral": "珊瑚",
    "wet skin": "湿皮肤",
    "cropped": "裁剪过的",
    "Extremely gorgeous metal style": "极其华丽的金属风格",
    "bad face": "坏面孔",
    "sakura": "樱花",
    "long face": "不高兴",
    "low quality background": "低质量背景",
    "backgroundbuilding architecture": "背景建筑建筑",
    "fused cloth": "熔结布",
    "clock": "时钟",
    "medium breast": "中胸",
    "christmas": "圣诞节",
    "bad mouth": "口臭",
    "wholeblack bloomer": "全黑初轧机",
    "tispy": "紧张的",
    "strapless dress": "无肩带连衣裙",
    "fusedfingers": "熔融手指",
    "3D game scene": "3D游戏场景",
    "lake in mountain stream": "山溪湖泊",
    "cracked mouth": "裂开的嘴",
    "silver armor": "银甲",
    "mutated hands and fingers :1.5.long body :1.3": "变异的手和手指：1.5.身长：1.3",
    "overexposure": "过度暴露",
    "scenery": "风景",
    "small breast": "小乳房5",
    "Metal details": "金属细节",
    "bust": "打破",
    "randomly distributed clouds": "随机分布的云",
    "ocean waves": "海浪",
    "starry sky in a circle": "星空环绕",
    "buttons": "按钮",
    "beatiful detailed cyberpunk city": "美丽细致的赛博朋克城",
    "missing clit": "缺少yin蒂",
    "Flame whirlpool": "火焰漩涡",
    "huge haunch": "大腰部",
    "very long blue and sliver hair": "非常长的蓝色和银色头发",
    "fine luminescence": "精细发光4",
    "mutation poorly drawn: 1.2": "突变绘制不佳：1.2",
    "hermaphrodite": "雌雄同体",
    "beautifully detailed sky": "美丽详细的天空2",
    "burning": "燃烧",
    "best quality": "最好的质量3",
    "Close up of people": "人物特写",
    "sketch": "素描",
    "Burning forest": "燃烧的森林",
    "azure hair": "蓝色头发",
    "huge ahoge": "巨大的洞穴",
    "disfigured": "毁容的",
    "bad breasts": "乳房不好",
    "liquid clit": "液体clit",
    "hair fluttering in the wind": "头发在风中飘动",
    "poorly drawn cum": "绘制不良cum",
    "beautiful detailed starry sky": "美丽详细的星空",
    "cross laced footwear": "交叉系带鞋",
    "extremely detailed face": "非常详细的面部",
    "beautiful detailed eyes": "美丽细腻的眼睛",
    "water bloom": "水华",
    "luminous eyes": "明亮的眼睛2",
    "worst low normal quality": "最低正常质量",
    "beatiful detailed hair": "美丽细致的头发2",
    "blank stare": "茫然凝视",
    "just like silver stars imploding we absorb the light of day": "就像银星内爆一样，我们吸收白天的光线",
    "detailed ice": "详细冰",
    "luminous particles": "发光粒子",
    "night": "夜",
    "one hand with less than 5 fingers": "一只手少于5个手指",
    "Beautiful golden eyes": "美丽的金色眼睛",
    "detailed beautiful desert with cactus": "有仙人掌的美丽沙漠",
    "mist encircles the mountains": "雾笼罩着群山",
    "mecha": "机甲",
    "dirty face": "肮脏的脸",
    "a silver triple crown inlaid with obsidian": "镶有黑曜石的银质三冠",
    "wand": "魔杖",
    "lolita": "洛丽塔",
    "Amazing": "太神了2",
    "gross proportions": "总比例",
    "Burn oneself in flames": "在火焰中自焚",
    "QR code": "二维码",
    "arms up": "举起手臂",
    "Violet dress with gold decoration": "金色装饰的紫色连衣裙",
    "sunrise": "日出",
    "long focus": "长焦距",
    "soft focus": "软焦点",
    "extra knee": "额外膝盖",
    "liquid breasts": "液体乳房",
    "on the battlefield": "在战场上",
    "dirty teeth": "脏牙",
    "medium chest circumference": "中等胸围",
    "lowres": "洛尔（lowres）",
    "Silky hair": "丝滑的头发",
    "Detailed crystallized clothing": "详细结晶服装",
    "Gothic Lolita": "哥特洛丽塔",
    "more than 2 nipples": "2个以上乳头",
    "strapless leotard": "无肩带紧身衣",
    "anime face": "动漫脸",
    "Fire cloud": "火云",
    "meteor": "流星",
    "Doomsday Scenes": "世界末日场景",
    "standing": "常设的",
    "fused digit": "融合数字",
    "sleeves past fingers": "袖子越过手指",
    "hime cut": "他剪的",
    "classic": "经典",
    "shit": "倒霉",
    "bad cameltoe": "坏骆驼趾",
    "willows with branches falling into the water": "树枝掉入水中的柳树",
    "more than 2 legs": "超过2条腿",
    "broken robot": "损坏的机器人",
    "colourful": "五颜六色的",
    "missing ears": "丢失的耳朵",
    "simple background": "简单背景",
    "Iridescence and rainbow eyes": "虹彩和彩虹眼",
    "poorly drawn asymmetric eyes": "画得不好的不对称眼睛",
    "huge filesize": "大文件大小",
    "castle": "城堡",
    "dusk": "黄昏",
    "Exquisite cloth": "精致的布料",
    "more legs": "更多的腿",
    "dargon wings": "达尔贡翼",
    "faeces": "粪便",
    "beautiful detailed hands": "漂亮细致的手",
    "Bracelet": "手镯6",
    "extremely detailed character": "极其详细的字符",
    "little girl": "小女孩13",
    "fused pussy": "融合阴部",
    "palace": "王宫",
    "Multi fingering": "多指操作",
    "three arms": "三个手臂",
    "detailed sunset glow": "详细的日落辉光",
    "Red Gem Necklace": "红色宝石项链",
    "other Minato aqua": "其他Minato aqua",
    "caustics": "焦散",
    "caustic": "腐蚀性的",
    "jacket": "夹克",
    "Luminous": "夜光的",
    "extra feet": "额外的脚",
    "black tongue": "黑色舌头",
    "duplicate": "复制",
    "ruins of city in war": "战争中的城市废墟",
    "extremely detailed CG": "非常详细的CG",
    "Burning sky": "燃烧的天空",
    "starfall": "星落",
    "Lavender eyes": "淡紫色眼睛",
    "beautiful detailed pampas grass field": "美丽细致的潘帕斯草地",
    "poorly drawn gloves": "拉伤的手套",
    "Broken glass": "破碎的玻璃",
    "more than 1 moon": "超过1个月亮",
    "poorly drawn face": "绘制不良的面",
    "Black hands": "黑手",
    "payot": "支付",
    "cumulus": "积云",
    "a hell on earth": "人间地狱",
    "detailed lighting": "详细照明",
    "stare": "盯着看",
    "Magical": "神奇的",
    "Multi foot": "多英尺",
    "yaoi": "雅依",
    "furry": "毛茸茸的5",
    "Fire butterflys": "火蝴蝶10",
    "very fine 8KCG wallpaper": "非常精致的8KCG壁纸",
    "Sputtered molten iron": "溅射铁水",
    "fused crotch": "融合胯部",
    "loong background": "龙背景",
    "frown": "皱眉",
    "war": "战争",
    "Beautifully gorgeous necklace": "漂亮华丽的项链",
    "stars": "星星",
    "burning feathers": "燃烧的羽毛",
    "Abnormal fingers": "手指异常",
    "beautiful detailed garden": "美丽精致的花园",
    "glowing eyes": "发光的眼睛",
    "hdr": "高密度橡胶",
    "flame": "火焰",
    "bad tentacles": "坏触角",
    "cape": "海角",
    "bad hands": "坏手",
    "fine water surface": "细水面",
    "finely detail": "精细的细节",
    "blurrylowres": "模糊香草",
    "bad gloves": "坏手套",
    "shadow": "阴影",
    "cute face": "可爱的脸",
    "Fire  butterflys": "火蝴蝶13",
    "Metal scratch": "金属划痕",
    "view straight on": "直视",
    "lowers": "降低",
    "Multifold": "多重",
    "colorful cameltoe": "彩色骆驼趾",
    "missing nipples": "乳头缺失",
    "bowknot": "蝴蝶结",
    "princess": "公主",
    "one hand with more than 5 digit": "一只手超过5位数",
    "Gradient color eyes": "渐变色眼睛",
    "Humpbacked": "驼背的3",
    "safety panties": "安全内裤2",
    "flowers": "鲜花",
    "long hair": "长发",
    "red eyes": "红色的眼睛",
    "JPEG artifacts": "JPEG伪影",
    "watermark": "水印",
    "finely detailed": "非常详细",
    "official art": "官方艺术",
    "worstquality": "最差品质",
    "master piece": "主件",
    "floating palace": "浮动宫殿2",
    "chromatic aberration": "色差",
    "malformed feet": "畸形足",
    "coast": "海岸",
    "moon": "月球",
    "extremely detailed sailor dress": "极其精致的水手服",
    "uncoordinated body": "不协调体",
    "extra digits": "额外的数字",
    "halter dress": "绕颈裙3",
    "liquid digit": "液体数字",
    "liquid animal ears": "液体动物耳朵",
    "alps": "阿尔卑斯山",
    "hidden hands": "隐藏的手",
    "Crystallize texture body": "结晶质感主体",
    "strong girl": "强壮的女孩",
    "2girls": "2个女孩",
    "Clothes made of silver": "银色衣服",
    "futa": "福塔",
    "missing fingers": "丢失的手指",
    "fusion hand": "融合手",
    "fused hand": "熔合手",
    "mechanical arm armor": "机械臂铠装",
    "beautiful detailed water": "美丽细腻的水",
    "extra digt": "额外挖掘3",
    "blcak metal helmet": "黑色金属头盔",
    "helmet": "头盔",
    "plateau": "高原",
    "World War": "第二次世界大战",
    "evil smile": "邪恶的微笑",
    "chain": "链条",
    "Black gauze skirt": "黑色纱布裙2",
    "Crystalline purple gemstone gloves": "水晶紫宝石手套",
    "poorly drawn pantie": "素描拙劣的内裤",
    "beautiful detailed lighting": "优美的细节照明",
    "extra eyes": "额外的眼睛",
    "red higanbana": "红希干巴纳",
    "bad legs": "腿不好",
    "Cape hood": "斗篷风帽",
    "surrounded by heavy floating sand flow and floating sharp stones": "周围是沉重的浮沙流和浮石",
    "very fine 8KCG wallpapers": "非常精细的8KCG壁纸",
    "poorly drawn tentacles": "拉得不好的触角",
    "long legs": "长腿",
    "Azur Lane": "Azur巷",
    "Neat tables and chairs": "整洁的桌椅",
    "cloned face": "克隆的脸",
    "resolute eyes": "坚定的眼睛",
    "sliver bodysuit": "银色紧身衣",
    "colorful refraction": "彩色折射",
    "bad pussy": "坏女人",
    "blue white skirt": "蓝白裙子",
    "anglesailor dress": "水手长连衣裙",
    "underboob": "车身底部",
    "glinting stars": "闪烁的星星",
    "lace flowing and melt": "花边流动和融化",
    "off shoulder": "露肩式",
    "flames of war": "战火",
    "world masterpiece theater": "世界杰作剧院",
    "delicate glow": "细腻的辉光",
    "medium breasts": "中等乳房",
    "pink pupils": "粉红色瞳孔",
    "bloom": "开花",
    "riding motor": "骑乘电动机",
    "wet clothes": "湿衣服",
    "3D game": "3D游戏",
    "nuclear explosion behide": "背后的核爆炸",
    "Standing on the surface of the sea": "站在海面上",
    "rain": "雨",
    "disreveled hair": "蓬乱的头发2",
    "White clothes": "白色衣服",
    "altocumulus": "高积云",
    "gross": "总的",
    "long neck": "长脖子",
    "long body: 1.3": "长机身2：1.3",
    "rainbow": "虹",
    "only lower body": "只有下半身",
    "lavender eyes": "淡紫色眼睛2",
    "fused thigh gap": "融合大腿间隙",
    "perfect and delicate limbs": "完美精致的四肢",
    "liquid body": "液体体",
    "morbid": "病态的",
    "black dress": "黑色连衣裙",
    "liquid thigh gap": "液体大腿间隙",
    "staring blankly": "茫然凝视2",
    "hiten 1": "白色1",
    "The detailed castle": "详细的城堡",
    "pointy ears": "尖尖的耳朵",
    "Hazy fog": "雾蒙蒙的",
    "text error": "文本错误",
    "watercolor 1girl": "水彩画1个女孩",
    "bad tails": "坏尾巴",
    "sad": "悲哀的",
    "smoke of gunpowder": "火药烟雾",
    "Cleavage": "乳沟",
    "holding wine gourd": "抱葫芦",
    "original": "起初的",
    "taiga": "针叶林",
    "Flames burning around": "周围燃烧着火焰",
    "mutated hands and fingers:1.5": "变异的手和手指4：1.5",
    "a blackhole behind the girl": "女孩身后的黑洞",
    "white stockings": "白色长袜2",
    "shine": "闪耀",
    "ukiyoe style": "浮世绘风格",
    "high quality snowflakes": "高品质雪花",
    "seabirds": "海鸟",
    "single human girl": "单身人类女孩",
    "fused eyes poorly drawn eyes": "融合眼画得不好",
    "petite": "娇小的",
    "big forhead": "大前额",
    "a dragon  stands behind the girl": "一条龙站在女孩后面",
    "bad thigh gap": "大腿间隙差",
    "missing feet": "丢失的脚",
    "optical illusion": "视错觉",
    "bad": "令人不快的",
    "ultra detailed": "超详细的",
    "cinematic lighting": "电影照明2",
    "Very long hair": "很长的头发",
    "whitegrey dress": "白灰色连衣裙",
    "magic circle": "魔法圆",
    "dark persona": "黑暗人物",
    "pleated skirt": "褶皱裙",
    "Negative prompt: Inverted mountain": "负提示：倒山",
    "Gelatinous texture": "凝胶状结构",
    "hollow night": "空虚的夜晚",
    "Exquisite Blood": "精致的血液",
    "magic circle:1": "魔法圆：1",
    "normal hands": "正常手",
    "filigree": "金银丝饰品",
    "half closed eyes": "半闭着的眼睛",
    "heavy ears": "沉重的耳朵",
    "veil": "面纱",
    "profile": "轮廓",
    "poorly drawn crotch seam": "拉得不好的胯缝",
    "mutated hand and finger: 1.5": "变异的手和手指：1.5",
    "one hand with more than 5 fingers": "一只手有5个以上的手指",
    "poorly drawn nipples": "拔得不好的乳头",
    "beautiful detailed  water": "美丽细腻的水3",
    "beautiful detailed girl": "漂亮细心的女孩",
    "miko": "米科",
    "detailed water": "详细的水",
    "distorted mountain": "扭曲的山",
    "long hair flowing with the wind": "随风飘动的长发",
    "Flames burning ice": "燃烧着冰的火焰",
    "Hair like melted metal": "头发状熔化金属",
    "bad pantie": "糟糕的内裤",
    "trans": "反式",
    "fused asshole": "保险丝混蛋",
    "bad crotch": "胯部不好",
    "ray tracing": "射线追踪",
    "bad leg": "腿不好2",
    "cute anime face": "可爱的动漫脸",
    "beauty detailed eye": "美容细心眼",
    "poorly drawn ears": "画得不好的耳朵",
    "spark": "火花",
    "grass": "草",
    "more transparent stars": "更透明的星星",
    "dynamic angle": "动态角度",
    "annoyed": "恼怒 的",
    "a cloudy sky": "多云的天空",
    "extra digit": "额外数字",
    "sharp face": "锐利的脸",
    "poorly drawn thigh gap": "大腿间隙拉得不好",
    "long sleeves": "长袖",
    "trannsexual": "变性的",
    "ice crystal texture wings": "冰晶纹理翅膀",
    "beautiful hair decoration": "漂亮的头发装饰",
    "multiple breasts": "多乳房",
    "missing breasts": "乳房缺失",
    "red streaked hair": "红色条纹头发",
    "sea of flowers": "花海",
    "medium wind": "中等风速",
    "a girl wears Clothes with a silver texture": "一个女孩穿着银色质地的衣服",
    "river": "河",
    "desert": "沙漠",
    "masterpiece": "杰作",
    "starry sky": "星空",
    "diamond and glaring eyes": "钻石和耀眼的眼睛",
    "floating glass fragments": "漂浮的玻璃碎片",
    "stocking": "长袜",
    "big top sleeves": "大袖上衣",
    "Inverted mountain": "倒置山",
    "bare stomach": "空腹",
    "detailed beautiful sky": "细腻美丽的天空",
    "super fine illustration": "超精细插图7",
    "burning hair": "燃烧的头发",
    "chain ring": "链环",
    "huge clocks": "巨大的时钟",
    "wort quality": "麦汁质量3",
    "Lace": "网眼织物",
    "extra shoes": "额外的鞋子",
    "polar lowres": "极地洛尔",
    "fused feet": "保险丝脚",
    "lowing hair": "低垂的头发",
    "bad cum": "不良cum",
    "long white hair": "长长的白发",
    "huge breasts": "巨大的乳房",
    "side blunt bangs": "侧面钝刘海",
    "bad nipples": "乳头不好",
    "flowing silver": "流动的银",
    "Tables and chairs in disarray": "杂乱的桌椅",
    "flowery meadow": "多花草地",
    "wavy silver hair": "波浪状银发",
    "an extremely delicate and beautiful": "极其精致和美丽",
    "shine eyes": "闪亮的眼睛",
    "snowpainting": "雪地绘画",
    "fused breasts": "融合乳房",
    "Detailed Glass shaped clothes": "详细的玻璃形状衣服",
    "open hakama": "开放式哈卡玛",
    "Dove of peace": "和平之鸽",
    "pentagram": "五角星形",
    "Glasses": "玻璃杯",
    "detailed cute anime face": "细致可爱的动漫脸",
    "watercolor medium": "水彩介质",
    "vines": "葡萄藤",
    "hairs between eyes": "眼睛之间的毛发",
    "nude": "裸体",
    "1 girl": "1个女孩2",
    "eyeball": "眼球",
    "ice and fire melt": "冰和火融化",
    "Black smoke": "黑烟",
    "fog": "雾",
    "Flying flames": "燃烧的火焰",
    "samurai": "武士",
    "with sword": "用剑",
    "missing digit": "缺少数字",
    "Lateral braid": "横向编织",
    "Smooth and radiant face": "光滑、容光焕发的面部",
    "heavy breasts": "沉重的胸部",
    "science fiction": "科幻小说",
    "bad body": "坏身体",
    "mosaic": "马赛克",
    "multiple leg": "多支腿",
    "Simple background": "简单的背景",
    "Metal wings": "金属机翼",
    "blue eyes": "蓝眼睛",
    "robot girl": "机器人女孩",
    "Sleeveles": "套筒",
    "liquid tongue": "液体舌头",
    "long hair blown up": "长发蓬乱",
    "close up": "闭合",
    "long body": "长车身",
    "clear sky": "晴朗的天空",
    "emotionless eyes": "无表情的眼睛",
    "Abnormal hands": "异常手",
    "very long hair": "很长的头发2",
    "solo": "独奏",
    "Rainbow in the sky": "天空中的彩虹",
    "bad animal ears": "坏的动物耳朵",
    "hoodie": "连帽衫",
    "detailed skeleton church": "详细的骨架教堂",
    "depth of field": "景深2",
    "fused seam": "熔接焊缝",
    "cinmatic lighting": "火焰照明",
    "wrinkled skirt": "皱褶裙",
    "feather": "羽毛",
    "sparkle": "闪烁",
    "burning sky": "燃烧的天空2",
    "highly detailed": "高度详细",
    "Ruins of beautiful details": "美丽细节的废墟",
    "Various metals background": "各种金属背景",
    "multiple digit": "多位数",
    "yellow hairpin": "黄色发夹",
    "Exquisite Flame": "精致的火焰",
    "missing asshole": "失踪的混蛋",
    "Flying petals": "飞舞的花瓣",
    "corner": "角",
    "floaing black feathers": "飘扬的黑色羽毛",
    "1girlan extremely delicate and beautiful girl": "1个极其娇嫩美丽的女孩",
    "beautiful detailed dark midnight sky": "美丽细腻的深夜天空",
    "heavy animal ears": "沉重的动物耳朵",
    "text": "文本",
    "Negative prompt: owres": "负提示：owres",
    "snow mountain": "雪山",
    "small breasts": "小乳房4",
    "fused face": "熔合面",
    "damaged classroom": "损坏的教室",
    "metal": "金属",
    "beautiful sky": "美丽的天空",
    "floating cloud:1.2": "浮云：1.2",
    "hood": "罩",
    "misty": "多雾的",
    "complex pattern": "复杂图案",
    "red mediumhair": "红色中毛",
    "snowflakesdetailed cute anime face": "雪花细节可爱的动漫脸",
    "dark intense shadows": "黑暗强烈的阴影",
    "messy white long hair": "凌乱的白色长发",
    "crystal": "结晶",
    "yellow eyes": "黄色的眼睛",
    "blue spark": "蓝色火花",
    "japanese clothes": "日本服装",
    "lighting particle": "照明粒子",
    "beautiful detailed black gothic Empire Waist Dress": "漂亮精致的黑色哥特式帝国腰围连衣裙",
    "long body :1.3": "长机身：1.3",
    "young girl": "年轻女孩",
    "poorly drawn shoes": "画得不好的鞋",
    "skeleton girl": "骷髅女孩",
    "detailed wet clothes": "详细的湿衣服",
    "dragon background": "龙的背景",
    "detailed light": "细节照明",
    "the best quality": "最好的质量",
    "nsfw": "新南威尔士州",
    "rainy days": "雨天",
    "pubic hair": "阴毛",
    "extremely detailed eyes and face": "非常细致的眼睛和脸",
    "death garden": "死亡花园",
    "fused animal ears": "融合动物耳朵",
    "colorful nipples": "彩色乳头",
    "missing thighs": "大腿缺失",
    "lantern": "灯笼",
    "abnormal feet abnormal fingers": "脚不正常手指不正常",
    "chain storm": "连锁反应风暴",
    "Splashing blood": "溅起的鲜血",
    "Depth of field": "景深",
    "Long hair": "长发2",
    "very delicate light": "非常微妙的光线",
    "lightning effect": "闪电效应",
    "fusion finger": "融合指",
    "starry Nebula": "星云",
    "super fine illustrations": "超精细插图",
    "black kneehighs:1.1": "黑色膝盖：1.1",
    "glass tint": "玻璃色调",
    "poorly drawn crotch": "拉得不好的胯部",
    "poorly drawn feet": "画得不好的脚",
    "Phoenix girl": "凤凰女孩",
    "black hair": "黑发",
    "fused mouth": "熔合口",
    "Beautiful and detailed explosion": "美丽而细致的爆炸",
    "angel": "天使",
    "anger": "愤怒",
    "blurry": "模糊不清的",
    "burning buildings": "燃烧的建筑物",
    "side view": "侧视图",
    "bad digit": "错误数字",
    "bad crotch seam": "胯部接缝不良",
    "midriff": "中音",
    "beautiful hair ornaments": "漂亮的发饰",
    "fluorescence": "荧光",
    "yokozuwari": "横滨县",
    "artifacts": "人工制品",
    "flowing iron": "流动铁",
    "too long tongue": "舌头太长",
    "breeze": "微风",
    "less stars form a circle": "更少的星星形成一个圆",
    "sleeves past wrists": "袖子穿过手腕",
    "Smooth and radiant skin": "光滑、容光焕发的肌肤",
    "surrounded by floating sakura": "被漂浮的樱花环绕",
    "watercolor": "水彩",
    "dream": "梦",
    "sit on the black throne": "坐在黑色的宝座上",
    "colorful": "丰富多彩的",
    "excrement": "粪便2",
    "jpeg artifacts": "jpeg工件3",
    "very detailed light": "非常详细的灯光",
    "Gem body": "宝石主体",
    "red and white flowers": "红色和白色的花",
    "photorealistic": "照片真实感",
    "jitome": "吉托姆",
    "black gauze skirt": "黑色纱布裙",
    "beautiful detailed gemstone sky": "美丽细致的宝石天空",
    "extremely detailed": "非常详细2",
    "large top sleeves": "大号上衣袖子",
    "missing animal ears": "缺少动物耳朵",
    "starfish": "海星",
    "blurred": "变模糊",
    "falling petals": "飘落的花瓣",
    "mutated": "变异的",
    "on beautiful detailed water": "美丽细腻的水2",
    "sitting on a blue star": "坐在蓝星上",
    "Covered in blood": "浑身是血",
    "nature": "自然界",
    "bad asshole": "坏混蛋",
    "beatiful detailed sliver dragon arnour": "美丽细腻的银龙阿诺",
    "bad collarbone": "锁骨不好",
    "Smooth skin": "光滑的皮肤",
    "extremely detailed cute anime face": "极其细致可爱的动漫脸",
    "peach pink pupils": "桃红色瞳孔",
    "painting": "绘画",
    "charactera girl": "性格女孩",
    "detailed face": "详细的表面",
    "eye shadow": "眼影",
    "sitting": "坐",
    "liquid ears": "液体耳朵",
    "detailed beautiful Snow Forest with Trees": "详细的美丽雪林和树木",
    "gross proportions. short arm": "总比例。短臂",
    "translucent fluttering skirt": "半透明飘逸裙",
    "Blood fog": "血雾",
    "female girl": "女女孩",
    "fighting": "战斗2",
    "huge calf": "巨大的小牛",
    "the best building": "最好的建筑",
    "beatiful detailed steet": "漂亮的细节steet",
    "ice and fire together": "冰和火在一起",
    "fire": "火",
    "darkside": "黑暗面",
    "thick coating": "厚涂层",
    "fused hairs": "融合毛发",
    "floating palaces:1.3": "浮动宫殿：1.3",
    "floating palaces:1.2": "浮动宫殿：1.2",
    "floating palaces:1.1": "浮动宫殿：1.1",
    "sexy body": "性感的身体",
    "medium bust": "中等胸围2",
    "bodysuit": "紧身衣",
    "fairyland": "仙境",
    "straight on": "直接向前",
    "lose leg": "失去一条腿",
    "Long dark blond hair": "深金色长发",
    "mutilated": "残缺不全的",
    "fused clit": "融合yin蒂",
    "more than 2 thighs": "2条以上大腿",
    "Girls\u0027 Front": "女孩正面",
    "bar code": "条形码",
    "poorly drawn asshole": "画得不好的混蛋",
    "french braid": "法式辫子",
    "bustier": "胸衣",
    "fused nipples": "熔融乳头",
    "missing collarbone": "锁骨缺失",
    "very close to viewer": "非常接近观众3",
    "long wavy curly hair": "长波浪卷发",
    "Cloud Map Plan": "云地图计划",
    "detailed cloud": "细节云",
    "white dress with pink lace with yellow decoration": "粉色蕾丝黄色装饰的白色连衣裙",
    "long yarn": "长纱线",
    "peg artifacts": "peg伪影",
    "bad anatomy disfigured malformed mutated": "解剖结构不良畸形变异",
    "fist": "拳",
    "leaning on huge stone": "靠在巨石上",
    "cute": "可爱的",
    "grossproportions": "总比例2",
    "monster girl": "怪物女孩",
    "rotating star sky": "旋转星空",
    "tranny": "特兰尼",
    "colored sclera": "彩色巩膜",
    "Floating ashes": "漂浮的灰烬",
    "mature female": "成熟女性",
    "poorly drawn animal ears": "画得不好的动物耳朵",
    "young girls": "年轻女孩2",
    "mouldy": "发霉的",
    "contour deepening": "等高线加深",
    "shiny hair": "闪亮的头发",
    "missing limb": "缺失的肢体",
    "expression": "表示",
    "poorly drawnhands": "抽汲能力差",
    "abnormal legs": "不正常的腿",
    "The residual eaves DuanBi": "残檐断壁",
    "monotone": "单调的",
    "flower": "花",
    "delicate wet skirt": "精致的湿裙子",
    "3D": "三维",
    "Thick hair": "浓密的头发",
    "loli": "洛丽",
    "fused anus": "融合肛门",
    "cloak": "斗篷",
    "incorrect limb": "不正确的肢体",
    "dark soul": "黑暗的灵魂",
    "extra breasts": "额外的乳房",
    "missing thigh gap": "大腿间隙缺失",
    "Mechanical wing": "机械机翼",
    "bad clit": "yin蒂不好",
    "missing fngers": "缺少fngers",
    "testis": "睾丸",
    "distorted light": "畸变光",
    "hair ribbon": "发带",
    "red plum blossom": "红色梅花",
    "amazing": "太神了",
    "beautiful detailed hair": "美丽细致的头发",
    "Metal texture": "金属纹理",
    "leaves": "叶子",
    "ui": "用户界面",
    "malformed mutated": "畸形突变",
    "white hair": "白发",
    "a lot of luminous ice crystals": "许多发光的冰晶",
    "floating hair": "漂浮的头发",
    "red rope": "红色绳索",
    "bad shoes": "坏鞋子",
    "looking at viewers": "观看观众",
    "extra fingers": "额外的手指",
    "Flying sparks": "飞溅的火花",
    "Cold machine": "冷机",
    "fused collarbone": "融合锁骨",
    "cracked floor": "有裂缝的地板",
    "beard": "胡须",
    "fused ears": "熔合的耳朵",
    "character focus": "字符焦点",
    "long bangs": "长刘海",
    "one hand with less than 5 digit": "一只手少于5位数",
    "posing sketch": "造型草图",
    "missing legs": "缺腿",
    "angry face": "愤怒的脸",
    "extra arms": "额外的武器",
    "beautiful detailed white gloves": "漂亮精致的白色手套",
    "Missing limbs": "缺少肢体",
    "tongue within mouth": "口中有舌",
    "4k": "4公里",
    "lens flare": "透镜光斑",
    "metal sense": "金属感测",
    "long bangs between eyes": "眼睛之间的长刘海",
    "extremely detailed 8K wallpaper": "非常详细的8K壁纸",
    "horns": "角2",
    "detailed flooding bare feet:1.5": "详细洪水裸脚：1.5",
    "Asymmetrical eyes": "不对称眼睛",
    "battleing": "战斗",
    "fused pantie": "熔接内裤",
    "bad anus": "肛门不好",
    "missing hand": "失去的手",
    "beautiful deatailed shadow": "美丽的去尾影",
    "glowworm": "萤火虫",
    "artist name": "艺术家姓名",
    "Flowers meadow": "鲜花草地",
    "mecha clothes": "机甲服",
    "censored": "审查",
    "Starry sky in beautiful detail": "美丽细节中的星空",
    "8k wallpaper": "8k壁纸",
    "cat ears": "猫耳",
    "black white": "黑白色",
    "bird see": "鸟瞰",
    "Bloodstain": "血痕",
    "sleepy": "困乏的",
    "disappearing arms": "消失的手臂",
    "bad anatomy": "解剖结构不好",
    "Iridescence and rainbow dress": "彩虹色连衣裙",
    "bowties": "蝴蝶结2",
    "Fire in eyes": "眼睛着火",
    "best shadow": "最佳阴影",
    "white dress": "白色连衣裙",
    "unclear eyes": "眼睛不清",
    "abnormal eye proportion": "眼睛比例异常",
    "missinglegs": "密森格格斯",
    "black kneehighs": "黑色膝盖",
    "flowery bubbles": "花状气泡",
    "cold smile": "冷笑",
    "too many fingers": "手指太多",
    "Iridescence and rainbow hair": "彩虹色和彩虹色头发",
    "Dead end machine": "死胡同机器",
    "best quality;highly detailed": "最佳质量；高度详细",
    "proportions": "比例",
    "Authentic skin texture": "真实的皮肤纹理",
    "feathers made of ice": "冰制羽毛",
    "game cg": "游戏cg",
    "cinematic angle": "电影角度",
    "green eyes": "绿眼睛",
    "Ambient light": "环境光",
    "beautiful detailed dress": "漂亮精致的连衣裙",
    "more than two shoes": "两双以上的鞋",
    "fingers": "手指",
    "deformed": "变形的，变形的",
    "Brilliant light": "明亮的灯光",
    "fused leg": "熔合支腿",
    "Please draw a picture of an exquisite girl in a princess dress with delicate gold metal decorations. She stands there looking at me": "请画一幅精美的女孩穿着公主裙，配上精致的金金属饰物。她站在那里看着我",
    "fused tentacles": "融合触角",
    "disappearing legs": "消失的腿",
    "bad ears": "耳朵不好",
    "from above": "从上面",
    "blue streaked hair": "蓝条纹头发",
    "dirty pantie": "脏内裤",
    "fused gloves": "熔接手套",
    "low quality": "低质量",
    "Exposing cleavage": "暴露解理",
    "extra legs": "额外的支腿",
    "upper body": "上半身",
    "extremely detailed CG unity 8k": "非常详细的CG统一8k",
    "extra limbs": "额外的肢体",
    "fused cum": "熔融cum",
    "Watercolor": "水彩2",
    "extremely detailed body": "极其详细的正文",
    "signature": "签名",
    "sailor dress": "水手服",
    "red and blue hair": "红色和蓝色头发",
    "poorly drawn cloth": "拉得不好的布",
    "church": "教堂",
    "light leaks": "漏光",
    "fireworks": "焰火",
    "low quality illustration": "低质量插图",
    "lovely big eyes": "可爱的大眼睛",
    "noon": "正午",
    "low quality mountain": "低质量山",
    "light blush": "浅腮红",
    "big mouth": "大嘴巴",
    "indoors": "在室内",
    "floating colorful bubbles": "漂浮的彩色泡泡",
    "poorly drawn hairs": "绘制不佳的头发",
    "asymmetrical bangs": "不对称刘海",
    "rivers": "河流",
    "Good looking flame": "漂亮的火焰",
    "extra animal ears": "额外的动物耳朵",
    "a lot of glowing particles": "大量发光粒子",
    "kogecha": "科格查",
    "The background is incoherent": "背景不连贯",
    "skull on dress": "连衣裙上的头骨",
    "cold attitude": "冷淡的态度",
    "messy hair": "头发乱了",
    "golden bracelet": "金手镯",
    "blonde hair": "金发",
    "messy hair style": "凌乱的发型",
    "sunlight": "阳光",
    "wings": "翅膀3",
    "an detailed organdie dress": "精致的欧根纱连衣裙",
    "multiple finger": "多指",
    "big muscles": "大肌肉",
    "float": "浮动2",
    "delicate wet dress": "精致的湿衣服",
    "blurry:1.1": "模糊：1.1",
    "Beautiful face": "漂亮的脸2",
    "Authentic and detailed face": "真实细致的面部",
    "short skirt": "短裙",
    "bad eyes": "眼睛不好",
    "mutated hands": "变异的手",
    "beatiful detailed eyes": "美丽细腻的眼睛2",
    "silk shawl": "丝绸披肩",
    "poorly drawn anus": "肛门拉伤",
    "unnatural body": "非自然身体",
    "Negative prompt: nsfw": "负提示：nsfw",
    "text font ui": "文本字体用户界面",
    "off shoulder jacket": "露肩夹克",
    "ugly": "丑陋的",
    "Blood drop": "血滴",
    "3D character": "3D字符",
    "beautiful detailed cold face": "美丽细致的冷面",
    "wavy hair": "波浪状头发",
    "solo focus": "单独聚焦",
    "abyssal ship": "深海船",
    "moonlight": "月光",
    "own hands clasped": "双手紧握",
    "Colorful blisters": "彩色水泡",
    "winter": "冬天",
    "grand feathers": "华丽的羽毛",
    "Wings on fire": "机翼着火",
    "bad feet hand finger leg eye": "脚不好手指脚眼",
    "error": "错误",
    "detailed light 1girl": "细节灯光1女孩",
    "burning cars": "燃烧的汽车",
    "flowing gold and silver": "流动的金银",
    "a girl inside the church with white hair and blue pupil surrounded by many glowing feathers in cold face": "教堂里的一个女孩，白头发，蓝瞳孔，周围长着许多发光的羽毛，脸上很冷",
    "liquid tentacles": "液体触手",
    "Flying splashes": "飞溅的水花",
    "floating": "浮动",
    "gorgeous bodysuit": "华丽的紧身衣",
    "Perfect details": "完美的细节",
    "poorly drawn :1.2": "绘制不良3：1.2",
    "limb": "肢",
    "beautiful detailed blue eyes": "美丽细致的蓝眼睛",
    "dreamland": "梦境",
    "poorly drawn mouth": "画得不好的嘴",
    "detailed eyes": "详细的眼睛",
    "Metal defects": "金属缺陷",
    "worst quality": "最差质量",
    "extremely detailed wallpaper": "非常详细的壁纸",
    "disfigured.bad anatomy disfigured": "毁容。解剖结构不良，毁容",
    "ink": "墨水",
    "an extremely delicate and beautiful girl": "一个极其娇嫩美丽的女孩",
    "Holy Light": "圣光",
    "owres": "欧维斯",
    "clothes": "衣服",
    "gold and sliver fringes": "金银流苏",
    "magical": "神奇的2",
    "malformed hands": "畸形手",
    "colorful background": "彩色背景",
    "Tulle lace white skirt Flowers and grass meadow": "薄纱蕾丝白色裙子鲜花和草地",
    "fused shoes": "熔接鞋",
    "Glass shaped texture hand": "玻璃状纹理手"
};